FROM node:24-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.30.3 --activate

COPY package.json .
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .
COPY turbo.json .

COPY apps/server/package.json ./apps/server/
COPY packages/types/package.json ./packages/types/
COPY packages/config/package.json ./packages/config/

RUN pnpm install

COPY . .

WORKDIR /app/apps/server

EXPOSE 3000

CMD ["pnpm", "dev"]
